---
coreos:
  units:
    - name: partition-disk.service
      command: start
      content: |
        [Unit]
        Description=Partitions the primary hd
        [Service]
        Type=oneshot
        ExecStart=/bin/bash -c 'echo -e "o\nn\np\n1\n\n\nw" | fdisk /dev/sda'
    - name: format-disk.service
      command: start
      content: |
        [Unit]
        Description=Formats the primary drive
        Requires=partition-disk.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/wipefs -f /dev/sda1
        ExecStart=/usr/sbin/mkfs.btrfs -f /dev/sda1
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount primary hd to /var/lib/docker
        Requires=format-disk.service
        Before=docker.service
        [Mount]
        What=/dev/sda1
        Where=/var/lib/docker
        Type=btrfs

write_files:
  - path: /tmp/bench_cpu_calc.sh
    permissions: 0755
    content: |
       #!/bin/bash
       # This image was uploaded to our private repository 
       # server for ease of testing.
       # It can be built from the Docker files at 
       # https://github.com/DockerDemos/vm-docker-bench\sysbench
       #
       # Tests CPU calculations by running a prime number 
       # calculation benchmark test in 100 Docker 
       # containers, serially.
       docker pull $REPO/sysbench
       for i in {1..100} ; do docker run -i -t $REPO/sysbench \
       --test=cpu --cpu-max-prime=20000 run |grep total\ time\: \
       | awk '{print $3}'| sed -i 's/s//g' ; done`

  - path: /tmp/bench_concurrent_spinup.sh
    permissions: 0755
    content: |
      #!/bin/bash
      # This image was uploaded to our private repository 
      # server for ease of testing.
      # It can be built from the Docker files at 
      # https://github.com/DockerDemos/vm-docker-bench
      #
      # Test Load, Memory, and I/O impact by starting 100 
      # Docker containers running an Apache server.
      #
      # This is also the base setup (100 waiting Apache servers)
      # for an Apache Bench (ab) test from 100 client servers located
      docker pull $REPO/webbench
      for i in {1..100} ; do docker run -d $REPO/webbench ; done

   - path: /tmp/bench_io_load.sh
     permissions: 0755
     content: |
      #!/bin/bash
      # This image was uploaded to our private repository 
      # server for ease of testing.
      # It can be built from the Docker files at 
      # https://github.com/DockerDemos/vm-docker-bench
      docker pull $REPO/iobench
      for i in {1..100} ; do docker run -d $REPO/iobench ; done

